name: Build HTML content from source

on:
  pull_request:
    branches:
      - '*'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

concurrency:
  group: "pages"
  cancel-in-progress: false

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - name: Setup bundler cache
        uses: actions/cache@caa296126883cff596d87d8935842f9db880ef25 # v5.1.0
        with:
          key: ${{ runner.os }}-bundler-${{ hashFiles('Gemfile.lock') }}
          path: .bundle/gems
      - name: Setup build cache
        uses: actions/cache@caa296126883cff596d87d8935842f9db880ef25 # v5.1.0
        with:
          key: ${{ runner.os }}-build
          path: __build
      - name: Setup Ruby
        uses: ruby/setup-ruby@95ef2b042f9d7a56d8268cba8559e2842e2ad01b # v1.321.0
        with:
          ruby-version: '3.3'
      - name: Install dependencies
        run: |
          sudo apt-get install imagemagick
          bundle config set --local path '.bundle/gems'
          bundle install
      - name: Build with Middleman
        run: |
          mkdir -p __build
          BUILD_OUTPUT="__build" bundle exec middleman build
      - name: Generate HTML Preview
        id: html_preview
        uses: pavi2410/html-preview-action@b58683c238478d5f8b5dacf4fe5e3f403afb449a # v5
        with:
          html_file: '__build/index.html'
      - name: Access preview
        run: echo "${STEPS_HTML_PREVIEW_OUTPUTS_URL}"
        env:
          STEPS_HTML_PREVIEW_OUTPUTS_URL: ${{steps.html_preview.outputs.url}}
